theme = "tokyonight_moon"

[editor]
line-number = "relative"

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

